In [1]:
#importing necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# importind data from local directory
data=pd.read_csv('E:/data_import/Myproject/Fake.csv')

In [3]:
data.head(10)

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   
5   Racist Alabama Cops Brutalize Black Boy While...   
6   Fresh Off The Golf Course, Trump Lashes Out A...   
7   Trump Said Some INSANELY Racist Stuff Inside ...   
8   Former CIA Director Slams Trump Over UN Bully...   
9   WATCH: Brand-New Pro-Trump Ad Features So Muc...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   
5  The number of cases of cops brutalizing and ki...    News   
6  Donald Trump spent a good portion of his day a...    News   
7  In the wake of yet another court decision that...    News   
8  Many people have raised the alarm regarding th...    News   
9  Just when you might have thought we d get a br...    News   

                date  
0  December 31, 2017  
1  December 31, 2017  
2  December 30, 2017  
3  December 29, 2017  
4  December 25, 2017  
5  December 25, 2017  
6  December 23, 2017  
7  December 23, 2017  
8  December 22, 2017  
9  December 21, 2017

In [4]:
data.tail()

title  \
23518  McPain: John McCain Furious That Iran Treated ...   
23519  JUSTICE? Yahoo Settles E-mail Privacy Class-ac...   
23520  Sunnistan: US and Allied ‘Safe Zone’ Plan to T...   
23521  How to Blow $700 Million: Al Jazeera America F...   
23522  10 U.S. Navy Sailors Held by Iranian Military ...   

                                                    text      subject  \
23518  21st Century Wire says As 21WIRE reported earl...  Middle-east   
23519  21st Century Wire says It s a familiar theme. ...  Middle-east   
23520  Patrick Henningsen  21st Century WireRemember ...  Middle-east   
23521  21st Century Wire says Al Jazeera America will...  Middle-east   
23522  21st Century Wire says As 21WIRE predicted in ...  Middle-east   

                   date  
23518  January 16, 2016  
23519  January 16, 2016  
23520  January 15, 2016  
23521  January 14, 2016  
23522  January 12, 2016

In [5]:
# data types of each column
data.dtypes

title      object
text       object
subject    object
date       object
dtype: object

In [6]:
# it indicates how many null values are present in each column
data.isnull().sum()

title      21
text       21
subject    42
date       42
dtype: int64

In [7]:
# it show how many rows and columns in our data set 
data.shape

(23523, 4)

In [8]:
#it shows how many different values are present in each column
data.nunique()

title      17914
text       17466
subject       17
date        1692
dtype: int64

In [9]:
# importind data from local directory
data1=pd.read_csv('E:/data_import/Myproject/True.csv')

In [10]:
data1.head()

title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   

                 date  
0  December 31, 2017   
1  December 29, 2017   
2  December 31, 2017   
3  December 30, 2017   
4  December 29, 2017

In [11]:
data1.shape

(21417, 4)

In [12]:
data1.isnull().sum()

title      0
text       0
subject    0
date       0
dtype: int64

# inserting our target column

In [13]:
data["target"] = 0    
# target value 0 means the job news is real
data1["target"] = 1   
# target value 1 means the job news is fake

In [14]:
data.head()

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   

                date  target  
0  December 31, 2017       0  
1  December 31, 2017       0  
2  December 30, 2017       0  
3  December 29, 2017       0  
4  December 25, 2017       0

In [15]:
data1.head()

title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   

                 date  target  
0  December 31, 2017        1  
1  December 29, 2017        1  
2  December 31, 2017        1  
3  December 30, 2017        1  
4  December 29, 2017        1

In [16]:
data.shape , data1.shape

((23523, 5), (21417, 5))

# Merging true and fake data frames

In [17]:
df=pd.concat([data,data1],axis=0)    
# now it merged in real and fake class

In [18]:
df.head(10)

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   
5   Racist Alabama Cops Brutalize Black Boy While...   
6   Fresh Off The Golf Course, Trump Lashes Out A...   
7   Trump Said Some INSANELY Racist Stuff Inside ...   
8   Former CIA Director Slams Trump Over UN Bully...   
9   WATCH: Brand-New Pro-Trump Ad Features So Muc...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   
5  The number of cases of cops brutalizing and ki...    News   
6  Donald Trump spent a good portion of his day a...    News   
7  In the wake of yet another court decision that...    News   
8  Many people have raised the alarm regarding th...    News   
9  Just when you might have thought we d get a br...    News   

                date  target  
0  December 31, 2017       0  
1  December 31, 2017       0  
2  December 30, 2017       0  
3  December 29, 2017       0  
4  December 25, 2017       0  
5  December 25, 2017       0  
6  December 23, 2017       0  
7  December 23, 2017       0  
8  December 22, 2017       0  
9  December 21, 2017       0

In [19]:
print(df['target'].unique())

[0 1]


In [20]:
df.shape

(44940, 5)

# Data cleaning

In [21]:
df.isnull().sum()

title      21
text       21
subject    42
date       42
target      0
dtype: int64

In [22]:
df.isnull().sum()

title      21
text       21
subject    42
date       42
target      0
dtype: int64

# Removing Unwanted columns

In [23]:
# we can't predict whether the news is fake or real using this column..only text column is enough for predicting the data
df.drop(['title','subject','date'],axis=1,inplace=True)

In [24]:
df.keys()

Index(['text', 'target'], dtype='object')

In [25]:
df.isnull().sum()

text      21
target     0
dtype: int64

In [26]:
#now the null values are deleted
df=df.dropna()

In [27]:
df.isnull().sum()

text      0
target    0
dtype: int64

In [28]:
df.head()

text  target
0  Donald Trump just couldn t wish all Americans ...       0
1  House Intelligence Committee Chairman Devin Nu...       0
2  On Friday, it was revealed that former Milwauk...       0
3  On Christmas day, Donald Trump announced that ...       0
4  Pope Francis used his annual Christmas Day mes...       0

In [29]:
df.shape

(44919, 2)

# Shuffling data frame in random manner

In [30]:
df=df.sample(frac=1)     
# we have to shuffle the class 0 and class1

In [31]:
df.head(10)

text  target
321    A backlash of epic proportions ensued after Do...       0
18609  Tim Allen took to Twitter to express his disap...       0
15838  Don t you know Obama would love to just throw ...       0
4626   WASHINGTON (Reuters) - President Donald Trump’...       1
18111  The wife of Fox News co-owner James Murdoch, m...       0
1966   Two anti-abortion activists are facing 15 felo...       0
19581  LONDON (Reuters) - The leaders of a far-right ...       1
3019   WASHINGTON (Reuters) - Nearly $1 trillion of t...       1
7740   Independent voter Chris Sullivan went to the p...       0
21962  Shawn Helton 21st Century Wire The gunman name...       0

In [32]:
# we shuffle the data from upper to lower..so the index value changed..it doesn't arranged in ascending order
df.reset_index(inplace=True)

In [33]:
df.head()

index                                               text  target
0    321  A backlash of epic proportions ensued after Do...       0
1  18609  Tim Allen took to Twitter to express his disap...       0
2  15838  Don t you know Obama would love to just throw ...       0
3   4626  WASHINGTON (Reuters) - President Donald Trump’...       1
4  18111  The wife of Fox News co-owner James Murdoch, m...       0

In [34]:
df.drop(['index'],axis=1,inplace=True)

In [35]:
df.head()

text  target
0  A backlash of epic proportions ensued after Do...       0
1  Tim Allen took to Twitter to express his disap...       0
2  Don t you know Obama would love to just throw ...       0
3  WASHINGTON (Reuters) - President Donald Trump’...       1
4  The wife of Fox News co-owner James Murdoch, m...       0

# Text Analysing

In [36]:
import string
import re

In [37]:
print(string.punctuation)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [38]:
def word(text):
    text = text.lower()    #we want to the convert our text into lower case
    text = re.sub('\[.*?\]', '', text)   #substitute these spacial character into empty space
    text = re.sub("\\W"," ",text)    #if any non-word character present it replaces that
    text = re.sub('https?://\S+|www\.\S+', '', text)   #it removes any google link or website,it replaced 
    text = re.sub('<.*?>+', '', text)   #these special cahracter also replaced with empty space..so these character will be removed
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)   #other than the above special character present in our text,it will replace
    text = re.sub('\n', '', text)   #if any \n means new line.it will replace
    text = re.sub('\w*\d\w*', '', text)    #if any number,non-word present in our text,it will replace
    return text

In [39]:
df['text']=df['text'].apply(word) #we have to apply the above text analyse in text data

In [40]:
df.head(10)

text  target
0  a backlash of epic proportions ensued after do...       0
1  tim allen took to twitter to express his disap...       0
2  don t you know obama would love to just throw ...       0
3  washington  reuters    president donald trump ...       1
4  the wife of fox news co owner james murdoch  m...       0
5  two anti abortion activists are facing  felony...       0
6  london  reuters    the leaders of a far right ...       1
7  washington  reuters    nearly   trillion of ta...       1
8  independent voter chris sullivan went to the p...       0
9  shawn helton  century wire the gunman named in...       0

# create Independent(Actual value) and Dependent variable(Target)

In [41]:
x=df['text']
y=df['target']

In [42]:
x.shape

(44919,)

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=101)

In [45]:
x_train.shape

(35935,)

# Convert text into Vectors

In [46]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [47]:
vectorization=TfidfVectorizer()   #machine learning doesn't understand text inputs..algorithm takes vactor as a input

In [48]:
xv_train=vectorization.fit_transform(x_train)
xv_test=vectorization.transform(x_test)

In [49]:
print(xv_train.shape)
print(y_train.shape)
print(xv_test.shape)
print(y_test.shape)

(35935, 97514)
(35935,)
(8984, 97514)
(8984,)


In [50]:
from sklearn.linear_model import LogisticRegression

In [51]:
lr=LogisticRegression()

In [52]:
lr.fit(xv_train,y_train)

LogisticRegression()

In [53]:
pred=lr.predict(xv_test)

In [54]:
pred[0:5]

array([1, 0, 0, 0, 0], dtype=int64)

In [55]:
y_test[0:5]

27070    1
33371    0
43972    0
41959    0
26255    0
Name: target, dtype: int64

In [56]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [57]:
print(classification_report(pred,y_test))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99      4643
           1       0.99      0.98      0.99      4341

    accuracy                           0.99      8984
   macro avg       0.99      0.99      0.99      8984
weighted avg       0.99      0.99      0.99      8984



In [58]:
print(confusion_matrix(pred,y_test))

[[4594   49]
 [  70 4271]]


In [59]:
accuracy_score(pred,y_test)

0.9867542297417632

In [60]:
from sklearn.tree import DecisionTreeClassifier

In [61]:
dc=DecisionTreeClassifier()

In [62]:
dc.fit(xv_train,y_train)

DecisionTreeClassifier()

In [63]:
pred1=dc.predict(xv_test)

In [64]:
pred1[0:5]

array([1, 0, 0, 0, 0], dtype=int64)

In [65]:
y_test[0:5]

27070    1
33371    0
43972    0
41959    0
26255    0
Name: target, dtype: int64

In [66]:
print(confusion_matrix(pred1,y_test))

[[4651   26]
 [  13 4294]]


In [67]:
print(classification_report(pred1,y_test))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00      4677
           1       0.99      1.00      1.00      4307

    accuracy                           1.00      8984
   macro avg       1.00      1.00      1.00      8984
weighted avg       1.00      1.00      1.00      8984



In [68]:
print(accuracy_score(pred1,y_test))

0.9956589492430988


# Model testing

In [69]:
def output_news(n):
    if n == 0:
        return "Real News"
    elif n == 1:
        return "Fake News"

In [77]:
def manual_testing(news):
    testing_news = {"text":[news]}  #create a column name
    new_test = pd.DataFrame(testing_news) #we have to create a text into dataframe
    new_test["text"] = new_test["text"].apply(word)  #we apply text cleaning
    new_x_test = new_test["text"]
    new_xv_test = vectorization.transform(new_x_test)
    pred = lr.predict(new_xv_test)
    pred1 = dc.predict(new_xv_test)
    print(f"prediction of news by using Logistic Regression is {output_news(pred)}")
    print(f'prediction of news by using decision tree is {output_news(pred1)}')

In [78]:
news = "can't say where good,but is,who can't replace"
manual_testing(news)

prediction of news by using Logistic Regression is Real News
prediction of news by using decision tree is Real News


In [79]:
manual_testing("PM narendira modi is our prime minister")

prediction of news by using Logistic Regression is Real News
prediction of news by using decision tree is Real News
